algorithm_name: mat
experiment_name: single
seed: -1
aseed: 1
cuda: true
cuda_deterministic: true
n_training_threads: 16
n_rollout_threads: 32
n_eval_rollout_threads: 1
n_render_rollout_threads: 1
num_env_steps: 2000000
use_wandb: false
wandb_project_name: mat_baseline
wandb_tag: debug
wandb_notes: null
env_name: butterfly
use_obs_instead_of_state: false
episode_length: 150
share_policy: true
use_centralized_V: true
stacked_frames: 4
use_stacked_frames: true
hidden_size: 64
layer_N: 2
use_ReLU: true
use_popart: false
use_valuenorm: true
use_feature_normalization: true
use_orthogonal: true
gain: 0.01
use_naive_recurrent_policy: false
use_recurrent_policy: false
recurrent_N: 1
data_chunk_length: 10
lr: 5.0e-05
critic_lr: ${lr}
opti_eps: 1.0e-05
weight_decay: 0
std_x_coef: 1
std_y_coef: 0.5
kl_threshold: 0.06
ls_step: 10
accept_ratio: 0.5
ppo_epoch: 10
use_clipped_value_loss: true
clip_param: 0.05
num_mini_batch: 1
entropy_coef: 0.01
value_loss_coef: 1
use_max_grad_norm: true
max_grad_norm: 0.5
use_gae: true
gamma: 0.99
gae_lambda: 0.95
use_proper_time_limits: false
use_huber_loss: true
use_value_active_masks: false
use_policy_active_masks: false
huber_delta: 10.0
use_linear_lr_decay: false
save_interval: 10000
log_interval: 5
use_eval: true
eval_interval: 10
eval_episodes: 32
save_gifs: false
use_render: false
render_episodes: 5
ifi: 0.1
model_dir: null
encode_state: false
n_block: 1
n_embd: 64
n_head: 1
dec_actor: false
share_actor: false
train_maps: null
eval_maps: null
scenario: prospector
map_name: ${scenario}
task: ${scenario}
n_agent: 4
add_move_state: false
add_local_obs: false
add_distance_state: false
add_enemy_action_state: false
add_agent_id: false
add_visible_state: false
add_xy_state: false
use_state_agent: false
use_mustalive: true
add_center_xy: false
work_dir: ./results

use_share_obs: true

# joint-predictive representation
use_jpr: false
jpr_ssl_tech: byol
use_linear_jprlr_decay: true
jpr_latent_dim: 512
jpr_projection_dim: ${n_embd}
use_aug_in_jpr: false
jpr_bsz: 128
jpr_jumps: 1
jpr_lr: ${lr}
jpr_update_freq: 1
jpr_target_update_freq: 1
jpr_momentum_tau: 0.01
jpr_mawm_n_head: 1
jpr_mawm_n_layer: 1
pre_transform_image_size: 100
image_size: 64

hydra:
  job_logging:
    root:
      level: ERROR
